config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#index'
  devise_for :users, skip: [:registrations], controllers: {
          sessions: 'users/sessions',
          passwords: 'users/passwords'
  }
  devise_for :clients, controllers: {
          sessions: 'users/sessions',
          passwords: 'clients/passwords'
          registrations: 'clients/registrations',
  }
  devise_for :admins, skip: [:registrations], controllers: {
          sessions: 'users/sessions',
          passwords: 'admins/passwords'
  }

  resources :cities
  resources :airports
  resources :airlines
  resources :flights

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html∫
end

app/models/airline.rb
class Airline < ApplicationRecord
end

app/models/airport.rb
class Airport < ApplicationRecord
  belongs_to :city, class_name: "City", foreign_key: "city_id"
  has_many :flights_by_origin , class_name: "Flight", foreign_key: "origin_airport_id"
  has_many :flights_by_destination, class_name: "Flight", foreign_key: "destination_airport_id"

  validates :name, :city_id, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
  has_many :airports, class_name: "Airport"
  validates :name, :country_name, :time_zone, presence: true
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :origin, class_name: "Airport", foreign_key: "origin_airport_id"
  belongs_to :destination, class_name: "Airport", foreign_key: "destination_airport_id"
  belongs_to :airline, class_name: "Airline", foreign_key: "airline_id"

  has_many :flight_itineraries, class_name: "FlightItinerary"
  has_many :planes, through: :itineraries

  validates :periodicity, :periodicity_time, :avg_time, presence: true

end

app/models/flight_itinerary.rb
class FlightItinerary < ApplicationRecord
end

app/models/passenger.rb
class Passenger < ApplicationRecord
end

app/models/plane.rb
class Plane < ApplicationRecord
  has_many :itineraries, class_name: "FlightItinerary"
  has_many :flights, through: :itineraries
  belongs_to :airline, class_name: "Airline", foreign_key: "airline_id"

  validates :code, :seats_b, presence: true
end

app/models/sale_order.rb
class SaleOrder < ApplicationRecord
end

app/models/ticket.rb
class Ticket < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  def index
    @airports = Airport.all
  end

  def show
    @airport = Airport.find_by(id: params[:id])
    if @airport.nil?
      flash[:error] = "Houston we are in troubles, please dont hack us."
      redirect_to root_path
    end
  end

  def new
    @airport = Airport.new
    @cities = City.all
  end

  def edit
    @airport = Airport.find_by(id: params[:id])
    @cities = City.all
    if @airport.nil?
      flash[:error] = "Houston we are in troubles, please dont hack us."
      redirect_to root_path
    end
  end

  def create
    @airport = Airport.new(airport_params)
    if @airport.save
      flash[:success] = "Airport created. Ok"
      redirect_to airports_path
    else
      @cities = City.all
      render 'new'
    end
  end

  def update
    @airport = Airport.find_by(id: params[:id])
    if @airport.update(airport_params)
      flash[:success] = "Airport created. Ok"
      redirect_to airports_path
    else
      @cities = City.all
      render 'edit'
    end
  end

  def destroy
    @airport = Airport.find_by(id: params[:id])
    if @airport.destroy
      flash[:success] = "Airport destroyed. Ok"
    else
      flash[:error] = "Houston we are in troubles, please dont hack us."
    end
    redirect_to airports_path
  end

  private

  def airport_params
    params.require(:airport).permit(:name, :city_id)
  end
end

app/controllers/plane_controller.rb
class PlaneController < ApplicationController
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/flight_helper.rb
module FlightHelper
end

app/helpers/plane_helper.rb
module PlaneHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vc_helper.rb
module VcHelper
  def current_user
    @current_user ||= current_client ? current_client : current_admin ? current_admin
  end
end

app/views/airports/_form.html.erb
<% form_name ||= "Manage" %>

<h2 class="text-center"> <%= form_name %> Airport </h2>
<%= form_for @airport , method: form_name.downcase == 'edit' ? 'put' : 'post' do |f| %>
<% if @airport.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@airport.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @airport.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <select name="airport[city_id]" >
      <% @cities.each do |c| %>
        <option value="<%= c.id %>"> <%= c.name %></option>
      <% end %>
    </select>
  </div>
    <%= f.submit "#{form_name} airport", class: "btn btm-primary" %>
    <a href="<%= airports_path %>" class="btn btn-default">View All airports</a>
<% end %>

app/views/airports/edit.html.erb
<div class="container">
  <%= render "form" , form_name: params[:action].capitalize %>
</div>

app/views/airports/index.html.erb
<div class="container">
  <h2 class="text-center"> AIRPOTS </h2>

    <article>
      <table class="table table-bordered table-responsive">
        <thead>
          <tr>
            <th>Name</th>
            <th>City</th>
            <th>Country</th>
            <th>Time Zone</th>
            <th>SHOW</th>
            <th>EDIT</th>
            <th>DELETE</th>
          </tr>
        </thead>
        <tbody>
          <% @airports.each do |a| %>
          <tr>
            <th><%= a.name %></th>
            <th><%= a.city.name %></th>
            <th><%= a.city.country_name %></th>
            <th><%= a.city.time_zone %></th>
            <th><a href="<%= airport_path(a.id) %>" data-method="get" class="btn btn-info" >Show</a></th>
            <th><a href="<%= edit_airport_path(a.id) %>" class="btn btn-warning" >Edit</a></th>
            <th><a href="<%= airport_path(a.id) %>" data-method="delete" class="btn btn-danger" >Delete</a></th>
          </tr>
          <% end if @airports.any? %>
        </tbody>
      </table>
      <a class="new-airport btn btn-default" href="<%= new_airport_path %>">New Airport</a>
    </article>

</div>

app/views/airports/new.html.erb
<div class="container">
  <%= render "form" , form_name: params[:action].capitalize %>

</div>

app/views/airports/show.html.erb
<div class="container">
  <h2 class="text-center"> AIRPORT </h2>

    <article>
      <table class="table table-bordered table-responsive">
        <thead>
          <tr>
            <th>Airport</th>
            <th>Country</th>
            <th>Time Zone</th>
            <th>EDIT</th>
            <th>DELETE</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th><%= @airport.name %></th>
            <th><%= @airport.city.country_name %></th>
            <th><%= @airport.city.time_zone %></th>
            <th><a href="<%= edit_airport_path(@airport.id) %>" class="btn btn-warning" >Edit</a></th>
            <th><a href="<%= airport_path(@airport.id) %>" data-method="delete" class="btn btn-danger" >Delete</a></th>
          </tr>
        </tbody>
      </table>
      <a class="new-airport btn btn-default" href="<%= new_airport_path %>">New airport</a>
      <a href="<%= airports_path %>" class="btn btn-default">View All Airports</a>
    </article>

</div>