config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#index'
  devise_for :users, skip: [:registrations], controllers: {
          sessions: 'users/sessions',
          passwords: 'users/passwords'
  }
  devise_for :clients, controllers: {
          sessions: 'users/sessions',
          passwords: 'clients/passwords'
          registrations: 'clients/registrations',
  }
  devise_for :admins, skip: [:registrations], controllers: {
          sessions: 'users/sessions',
          passwords: 'admins/passwords'
  }

  resources :cities
  resources :airports
  resources :airlines
  resources :flights

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html∫
end

app/models/airline.rb
class Airline < ApplicationRecord
end

app/models/airport.rb
class Airport < ApplicationRecord
  belongs_to :city, class_name: "City", foreign_key: "city_id"
  has_many :flights_by_origin , class_name: "Flight", foreign_key: "origin_airport_id"
  has_many :flights_by_destination, class_name: "Flight", foreign_key: "destination_airport_id"

  validates :name, :city_id, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
  has_many :airports, class_name: "Airport"
  validates :name, :country_name, :time_zone, presence: true
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :origin, class_name: "Airport", foreign_key: "origin_airport_id"
  belongs_to :destination, class_name: "Airport", foreign_key: "destination_airport_id"
  belongs_to :airline, class_name: "Airline", foreign_key: "airline_id"

  has_many :flight_itineraries, class_name: "FlightItinerary"
  has_many :planes, through: :itineraries

  validates :periodicity, :periodicity_time, :avg_time, presence: true

end

app/models/flight_itinerary.rb
class FlightItinerary < ApplicationRecord
end

app/models/passenger.rb
class Passenger < ApplicationRecord
end

app/models/plane.rb
class Plane < ApplicationRecord
  has_many :itineraries, class_name: "FlightItinerary"
  has_many :flights, through: :itineraries
  belongs_to :airline, class_name: "Airline", foreign_key: "airline_id"

  validates :code, :seats_b, presence: true
end

app/models/sale_order.rb
class SaleOrder < ApplicationRecord
end

app/models/ticket.rb
class Ticket < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)
    if @city.save
      redirect_to cities_path
    else
      render "new"
    end
  end

  def show
    find_city
    if @city.nil?
      flash[:error] = "Houston we have a problem! Try Later!"
      redirect_to root_path
    end
  end

  def edit
    find_city
  end

  def update
    find_city
    if @city.update(city_params)
      redirect_to cities_path
      flash[:success] = "City UPDATED Successfully!"
    else
      flash[:error] = "Houston we have a problem! Try Later!"
      render "edit"
    end
  end

  def destroy
    find_city
    if @city.destroy
      flash[:success] = "City Delete Successfully!"
    else
      flash[:error] = "Houston we have a problem! Try Later!"
    end
    ##binding.pry
    redirect_to cities_path
  end

  private

  def find_city
    @city = City.find_by(id: params[:id])
  end
  #strong parameters
  def city_params
      params.require(:city).permit(:name, :country_name, :time_zone)
  end
end

app/controllers/plane_controller.rb
class PlaneController < ApplicationController
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/flight_helper.rb
module FlightHelper
end

app/helpers/plane_helper.rb
module PlaneHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vc_helper.rb
module VcHelper
  def current_user
    @current_user ||= current_client ? current_client : current_admin ? current_admin
  end
end

app/views/cities/_form.html.erb
<% form_name ||= "Manage" %>
    <h2 class="text-center"> NEW CITY </h2>
    <%= form_for @city , method: form_name.downcase == 'edit' ? 'put' : 'post' do |f| %>

    <% if @city.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@city.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @city.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :country_name %>
        <%= f.text_field :country_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :time_zone %>
        <%= f.text_field :time_zone, class: "form-control" %>
      </div>
        <%= f.submit "#{form_name} city", class: "btn btm-primary" %>
        <a href="<%= cities_path %>" class="btn btn-default">View All Cities</a>
<% end %>

app/views/cities/edit.html.erb
<div class="container">
  <%= render "form" , form_name: params[:action].capitalize %>
</div>

app/views/cities/index.html.erb
<div class="container">
  <h2 class="text-center"> CITIES </h2>

    <article>
      <table class="table table-bordered table-responsive">
        <thead>
          <tr>
            <th>City</th>
            <th>Country</th>
            <th>Time Zone</th>
            <th>SHOW</th>
            <th>EDIT</th>
            <th>DELETE</th>
          </tr>
        </thead>
        <tbody>
          <% @cities.each do |c| %>
          <tr>
            <th><%= c.name %></th>
            <th><%= c.country_name %></th>
            <th><%= c.time_zone %></th>
            <th><a href="<%= city_path(c.id) %>" data-method="get" class="btn btn-info" >Show</a></th>
            <th><a href="<%= edit_city_path(c.id) %>" class="btn btn-warning" >Edit</a></th>
            <th><a href="<%= city_path(c.id) %>" data-method="delete" class="btn btn-danger" >Delete</a></th>
          </tr>
          <% end if @cities.any? %>
        </tbody>
      </table>
      <a class="new-city btn btn-default" href="<%= new_city_path %>">New City</a>
    </article>

</div>

app/views/cities/new.html.erb
<div class="container">
  <%= render "form" , form_name: params[:action].capitalize %>
</div>

app/views/cities/show.html.erb
<div class="container">
  <h2 class="text-center"> CITY </h2>

    <article>
      <table class="table table-bordered table-responsive">
        <thead>
          <tr>
            <th>City</th>
            <th>Country</th>
            <th>Time Zone</th>
            <th>EDIT</th>
            <th>DELETE</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th><%= @city.name %></th>
            <th><%= @city.country_name %></th>
            <th><%= @city.time_zone %></th>
            <th><a href="<%= edit_city_path(@city.id) %>" class="btn btn-warning" >Edit</a></th>
            <th><a href="<%= city_path(@city.id) %>" data-method="delete" class="btn btn-danger" >Delete</a></th>
          </tr>
        </tbody>
      </table>
      <a class="new-city btn btn-default" href="<%= new_city_path %>">New City</a>
      <a href="<%= cities_path %>" class="btn btn-default">View All Cities</a>
    </article>
</div>